
// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.


//***********NEED TO FINISH AND WORK IT OUT *********//

var findTheDifference = function (s, t) {
    let sortedS = s.split('').sort();
    let sortedT = t.split('').sort();

    for (let i = 0; i < sortedT.length; i++) {
        if (sortedS[i] != sortedT[i]) {
            return sortedT[i];
        }
    }
};

console.log(findTheDifference("abcd", "abcde"))
console.log(findTheDifference("", "y"))
console.log(findTheDifference("mlkj", "jtklm"))